<?php

return [
    'roles' => [
        'owner' => [
            'label' => 'Owner',
            'permissions' => ['*'],
        ],
        'admin' => [
            'label' => 'Admin',
            'permissions' => [
                'contacts.view', 'contacts.create', 'contacts.update', 'contacts.delete', 'contacts.export',
                'contacts.import',
                'companies.view', 'companies.create', 'companies.update', 'companies.delete', 'companies.export',
                'deals.view', 'deals.create', 'deals.update', 'deals.delete', 'deals.export',
                'deals.import',
                'projects.view', 'projects.create', 'projects.update', 'projects.delete',
                'buildings.view', 'buildings.create', 'buildings.update', 'buildings.delete',
                'apartments.view', 'apartments.create', 'apartments.update', 'apartments.delete',
                'apartments.import', 'apartments.export',
                'pipelines.view', 'pipelines.create', 'pipelines.update', 'pipelines.delete',
                'activities.view', 'activities.create', 'activities.update', 'activities.delete',
                'notes.view', 'notes.create', 'notes.update', 'notes.delete',
                'tags.view', 'tags.create', 'tags.update', 'tags.delete',
                'team.view', 'team.update', 'team.members.invite', 'team.members.remove', 'team.members.update_role',
                'custom_fields.view', 'custom_fields.create', 'custom_fields.update', 'custom_fields.delete',
                'reports.view',
            ],
        ],
        'member' => [
            'label' => 'Member',
            'permissions' => [
                'contacts.view', 'contacts.create', 'contacts.update',
                'companies.view', 'companies.create', 'companies.update',
                'deals.view', 'deals.create', 'deals.update',
                'projects.view', 'projects.create', 'projects.update',
                'buildings.view', 'buildings.create', 'buildings.update',
                'apartments.view', 'apartments.create', 'apartments.update',
                'pipelines.view',
                'activities.view', 'activities.create', 'activities.update', 'activities.delete',
                'notes.view', 'notes.create', 'notes.update', 'notes.delete',
                'tags.view',
                'team.view',
                'custom_fields.view',
                'reports.view',
            ],
        ],
        'viewer' => [
            'label' => 'Viewer',
            'permissions' => [
                'contacts.view',
                'companies.view',
                'deals.view',
                'projects.view',
                'buildings.view',
                'apartments.view',
                'pipelines.view',
                'activities.view',
                'notes.view',
                'tags.view',
                'team.view',
                'custom_fields.view',
                'reports.view',
            ],
        ],
    ],
];
